name: Run Tests

# Run this workflow on every push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs to be run in this workflow
jobs:
  test:
    # Runs the job on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Check out the repository code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version, like '3.9'

      # Run tests
      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p 'test_*.py'
